### ISSUE TITLE
no-basis-Address/country og ISO 3166

### ISSUE THREAD

**Issue by rockphotog** [HL7Norway/basisprofiler-r4#1]
Stille krav til tokoders ISO 3166, evt bruke trekoders hvis det ikke finnes tokoders. 

Tekst fra IPS:

> pat-cnt-2or3-char: The content of this element SHALL be selected EITHER from ValueSet ISO Country Alpha-2 http://hl7.org/fhir/ValueSet/iso3166-1-2 OR MAY be selected from ISO Country Alpha-3 Value Set http://hl7.org/fhir/ValueSet/iso3166-1-3, IF the country is not specified in value Set ISO Country Alpha-2 http://hl7.org/fhir/ValueSet/iso3166-1-2

Kilde:
https://build.fhir.org/ig/HL7/fhir-ips/StructureDefinition-Patient-uv-ips.html

**Comment by frankaberger** [comment]
Støttes av HSØ. ADT batteriet i HSØ baserer seg i dag på tokoders landskoder

**Comment by thomiz** [comment]
Folkeregisteret benytter idag Alpha 2 for landkoder i adresse og alpha 3 for alle andre nasjonalitetskoder (statsborgerskap, innflytting fra, utflytting til, identifiserende informasjon, sivilstand utland, fødsel utland og identifikasjonsdokument utstederland). Grunndatamodellen legger seg på samme linje, men slik jeg leser det har ikke IPS noen hard kobling til kodeverkene og kodene kan dermed ikke valideres. Jeg så for meg noe lignende i Grunndataprofilene, altså en løs kobling til http://hl7.org/fhir/ValueSet/iso3166-1-3 og/eller http://hl7.org/fhir/ValueSet/iso3166-1-2
9043 og 8460 angir vel disse på Volven, men jeg foreslår at vi ikke benytter Volvenkodene her.

**Comment by thomiz** [comment]
Hvis vi skal stramme inn landkodebruk bør vi gjøre det nå med oppdatering til R4.

**Comment by thomiz** [comment]
Det er ingen harde/validerbare krav om landkoder i Address.Country. Elementet er av typen string, så validerbare krav kan egentlig ikke implementeres. Vi kunne endret til Code/Coding, men da bryter vi med den underliggende standarden og det ønsker vi ikke å gjøre.
