### ISSUE TITLE
LES MEG

### ISSUE THREAD

**Issue by rockphotog** [HL7Norway/basisprofiler-r4#10]
Alle issues/spørsmål som ikke gjelder basisprofiler kan med fordel legges som [issues under
best practice](https://github.com/HL7Norway/best-practice/issues).

**Comment by oaassv** [comment]
Håper dette anvendes i praksis nå.

**Comment by rockphotog** [comment]
Ja, dette var egentlig en "sticky" - til evig påminnelse.
