### ISSUE TITLE
Encounter.class mapping til 8406

### ISSUE THREAD

**Issue by thomiz** [HL7Norway/basisprofiler-r4#102]
Standarden sier v3.ActEncounterCode og extensible, Coding er 1..1
I Norge benytter vi Volven 8406.

Hva er overlappet her?
Hva skal defineres i basisprofilen?
Handler 8406 og ActEncounterCode om det samme?
Passer 8406 i Encounter.class?

**Comment by oaassv** [comment]
Settes på agenda i TSK i uke 49

**Comment by oaassv** [comment]
Kort oppsummert:
Volven 8406 har 4 koder (inneliggende, poliklinisk, dagbehandling og polikliniske radiologi ++). ActEncounterCode har en rekke koder, men bare to tilsvarer kodene i 8406 - IMP for inneliggende, og AMB for poliklinisk. Så vi har overlapp på to koder, og to koder i 8406 som ikke finnes i det extensible HL7 kodeverket ActEncounterCode. I forhold til rapportering bør vi forholde oss til kodeverdiene i 8406, i forhold til samhandling bør vi forholde oss til kodeverdiene i ActEncounterCode der det er overlapp. Hvordan definerer vi ValueSettet?

**Comment by cgerno** [comment]
So vidt jeg husker er ValueSet en vanlig ressurs (http://hl7.org/fhir/valueset.html), og jeg anbefaler bruker Extensional definition, also det er bare å liste opp enhver kode.

**Comment by oaassv** [comment]
Lagt inn spørsmål om Shortstay på chat-en:
https://chat.fhir.org/#narrow/stream/179202-terminology/topic/ShortStay.20in.20SetActEncounterCode

**Comment by oaassv** [comment]
Konkret forslag basert på tilbakemeldinger:
- Etablere et ValueSet - no-basis-SetActEncounterCode med AMB og IMP + to norske ekstensjoner DT (day treatment) som child av SS og AMBR (poliklinikk radiologi ++) som child av AMB. 
- Mapping til Volven-koder skjer i mappingsegmentet i basisprofilen.

**Comment by thomiz** [comment]
Endre mapping linjen til:
* Mapping til Volven-koder skjer i ConceptMap definisjon som legges til no-basis enten som draft (ikke standard), eller som active (en del av standarden)

**Comment by thomiz** [comment]
Binding mot det norske value-settet blir fremdeles extensible.
* Hva betyr det om vi utelater koder fra det internasjonale kodeverket fra det norske valuesettet? 
  * Det er OK
* Tar vi bare med de kodene fra 8406 som ikke overlapper i det norske valuesettet? 
  * nei ingen norske koder i valuesettet, internasjonale koder går i instansene

Det Norske valuesettet inneholder bare:
* AMB tilsvarer 8406 - 3
* IMP tilsvarer 8406 - 1
* extension DT (tilsvarer 2)
* extension AMBR (tilsvarer 4)

Mappingen mellom 8406 og internasjonale koder dokumenteres i ConceptMap'et

**Comment by oaassv** [comment]
Thomas oppsummerer over godt forslaget fra TSK-møte 16.desember. Prosjektet utarbeider konkret profileringsforslag med dette som utgangspunkt og presenterer for avstemning på neste TSK-møte.

**Comment by oaassv** [comment]
Lagt inn UTG Change proposal for DT-kode.
https://jira.hl7.org/browse/UP-270

**Comment by thomiz** [comment]
Lukker denne, no-basis-Enconter er ikke på trappene nå.
