### ISSUE TITLE
Encounter.priority og bruk av Volven 8428

### ISSUE THREAD

**Issue by thomiz** [HL7Norway/basisprofiler-r4#103]
no-basis-Encounter har profilert priority til extensible (FHIR har example på sin binding til v3.ActPriority kodeverket) 

* Basisprofilen kan ikke ha skru til profileringen til extensible, det blir for snevert for no-basis
* Bruk av **Volven kodeverk 8428 - Hastegrad** bør foreslås som en åpen slice på Coding (priority er 0..1 og kan ikke slices direkte)

**Comment by helgaarm** [comment]
Jeg trur ikke vi bør stenge denne issuen - kan vi diskutere den ? 8428 er ikke godt kodeverk for dette selv om det kan fungere i noen tilfeller. Det er spørsmål om vi bør profilere noe på hastegrad eller om vi heller skal overlate det til implementerte profiler.

**Comment by rockphotog** [comment]
Jeg er enig at det bør foreligge et generisk/standardisert verdisett for dette, gjerne der 8428 (som er for NPR) er et rent subsett. Noe K&T / @josteinven & kan se på? 

På den annen side, open slicing på 8428 er ok hvis det er noenlunde sannsynlig at den blir bruk i underliggende profiler, men... ja, kanskje greiest i mer spisse profiler. Hehe, "tenker" mens jeg skriver.

**Comment by thomiz** [comment]
Lukker denne, no-basis-Encounter er ikke på trappene nå.
