### ISSUE TITLE
Appointment.appointmentType slicing

### ISSUE THREAD

**Issue by thomiz** [HL7Norway/basisprofiler-r4#104]
Det kan ikke være Closed slicing på AppointmentType.coding. Slicen må være åpen.

**Comment by helgaarm** [comment]
Slicen er åpen nå. I utgangspunktet er de 3 kodeverk som er foreslått dårlig egnet for appointmentType men de er de beste som vi har nasjonalt. NHN foreslår ett nytt valuesett i sin implementasjon.
