### ISSUE TITLE
Appointment group extension

### ISSUE THREAD

**Issue by thomiz** [HL7Norway/basisprofiler-r4#106]
Er denne overflødig hvis man får inn gruppe i Appointment.participant?
[HL7 Jira participant issue](https://jira.hl7.org/browse/FHIR-34141)

**Comment by rockphotog** [comment]
Hvis jeg forsto riktig er extension "gruppetime(boolean)" mer som en opplysning til f.eks. innbygger, og det er nødvendigvis ikke noe eksplisitt info om andre deltagere i Appointment.participant.

**Comment by oaassv** [comment]
Det er riktig - ren info til pasient/ innbygger om at det er en gruppesesjon.

**Comment by helgaarm** [comment]
Ikke noen kommentarer som jeg veit om i de runder som vi har hatt på profilen
