### ISSUE TITLE
Appointment partOf extension

### ISSUE THREAD

**Issue by thomiz** [HL7Norway/basisprofiler-r4#107]
* Sjekk at Jira er opprettet? 
* Trenger vi denne extension hvis det kommer ny funksjonalitet i R5?
* [Chat om saken og eventuell R5 funksjonalitet](https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Extend.20Appointment.20with.20partOf)

**Comment by rockphotog** [comment]
Behovet i R4 vil jo være der. Hvis det kommer i R5 bør extension for R4 være så lik som mulig, fortrinnsvis da en internasjonal extension.

**Comment by helgaarm** [comment]
partOf finnes ikke i R5 og sannsynlig vis ikke heller i R6. Extension er for å møte behov for å skille i mellom timeavtale og underliggende timer. Den måten å tenke på er ikke generisk, men løser behov som deler av spesialisthelse har.
