### ISSUE TITLE
Mulige saker til WGM 18-20 januar 2022

### ISSUE THREAD

**Issue by thomiz** [HL7Norway/basisprofiler-r4#109]
* Utvidelser av Appointment
  * bedre støtte for virtuelle appointments/virtuelle lokasjoner
  * Korrekt bruk a Location/virtuelle Locations 
* Bruke HER-id i MessageHeader, meldingsadressering til identifikator (i motsetning til endepunkt med en kjent adresse/url)

[Appointment diskusjon no-basis](https://github.com/HL7Norway/basisprofiler-r4/issues/105)

**Comment by thomiz** [comment]
Virtuelle locations/appointments hva skal stå i Jira saken?

Problemstilling: Virtuelle appointments hvor kommunikasjon kan gå via mange forskjellige løsninger. Ikke en enkel forståelig entydig måte å løse dette på. Bør være en permanent løsning for dette som en del av standarden (80/20).
Begynne med standard [extension](http://www.healthintersections.com.au/?p=3017) for endepunkt, evt. integrere dette som en del av standarden (Appointment element) i R5.


* Dansk løsning
* Australiensk løsning

Forslag:
* Foreslå ett nytt element (ContactPoint eventuellt en ny struktur under et BackboneElement for å uttrykke endepunkter til møtet) til Appointment for endepunkt/kontakt for virtuelle møter
* Benytte HealthcareService (i participant) til eventuelle generelle metadata om den virtuelle tjenester

Hva med Endpoint? Antakelig ikke relevant for konkrete endepunkter til møter.

**Comment by thomiz** [comment]
[Jira sak 34978](https://jira.hl7.org/browse/FHIR-34978)  

Please review @rockphotog @kennethmyhra @oaassv

**Comment by thomiz** [comment]
@kennethmyhra Endepunkt på norsk mener jeg er litt mer generelt begrep enn definisjonen av Endpoint ressursen. Så nei, jeg mener ikke Endpoint når jeg skriver endepunkt over. Kunne godt hatt en annen formulering for å gjøre det mer tydelig.

**Comment by oaassv** [comment]
👍

**Comment by rockphotog** [comment]
Litt rar setning: "The Norwegian are building a common infrastructure(...)"

**Comment by kennethmyhra** [comment]
Jeg la ikke mer til lenken til Jira-saken i går...

Kun litt småpirk

Kan vi endre denne fra:
> The resource definition does not support this use-case in a well defined way

til:
> The resource definition does not support the virtual appointment use-case in a well defined way

Forslag til setningen Espen påpeker:
> The Norwegian community is currently profiling common national profiles for booking appointments (...)

**Comment by oaassv** [comment]
Saken er allokert til torsdag q2 på WGM.

**Comment by thomiz** [comment]
Jeg vet ikke om jeg kan stille på WGM siden ingen av mine betalingskort blir akseptert av HL7 sin betalingsløsning. Visakortet jeg brukte til dette tidligere er utgått og ingen av MasterCard'ene (credit og debit) mine virker hos HL7 (til tross for at det er åpent for netthandel og i Nord-Amerika, og jeg får betalt med dem på ebay og Amazon).

Derfor kan noen av dere andre forberede dere til å diskutere denne saken på WGM i mitt fravær? @kennethmyhra @rockphotog @oaassv

**Comment by oaassv** [comment]
Veldig merkelig! Kan jeg evt legge ut?
    På lørdag 15. januar 2022, 10:25:43 CET skrev Thomas Tveit Rosenlund ***@***.***> følgende:  
 
 


Jeg vet ikke om jeg kan stille på WGM siden ingen av mine betalingskort blir akseptert av HL7 sin betalingsløsning. Visakortet jeg brukte til dette tidligere er utgått og ingen av MasterCard'ene (credit og debit) mine virker hos HL7 (til tross for at det er åpent for netthandel og i Nord-Amerika, og jeg får betalt med dem på ebay og Amazon).

Derfor kan noen av dere andre forberede dere til å diskutere denne saken på WGM i mitt fravær? @kennethmyhra @rockphotog @oaassv

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by thomiz** [comment]
**OFF TOPIC**
God ide @oaassv

Tror jeg skal spørre om kona har et visa kort jeg kan forsøke først, siden jeg sikkert trenger fullt kort-nummer og CRC for å få betalingen til å gå igjennom.
**OFF TOPIC**

**Comment by thomiz** [comment]
Vi får endringer til R5 for Appointment.
