### ISSUE TITLE
no-basis-address/city|bydel

### ISSUE THREAD

**Issue by frankaberger** [HL7Norway/basisprofiler-r4#11]
Oslo er oppdelt i bydeler, der bydelene er tildelt en del oppgaver, noe også de andre største byene i Norge er. Bør vi legge til en extension i no-basis-adress for bydel, eller bør den legges til i en annen profil. 

Bruksområder
- Informasjon for å initiere elektronisk kommunikasjon med korrekt bydel
- Henting av person fra folkeregisteret, både til spesialisthelsetjenesten, men også andre aktører som har tilgang til å gjøre oppslag mot folkeregistertjenesten på Helseplattformen/Nasjonalt

**Comment by rockphotog** [comment]
Vi har laget en extension urbanDistrict
https://simplifier.net/hl7norwayno-basis/nobasisurbandistrict

Den lå vel på pasient, men skal vel ligge under adresse - @thomiz  ?

**Comment by thomiz** [comment]
Ja, dette ligger i siste versjon av no-basis-Address og er flyttet ut av no-basis-Patient. Folkeregisteret inneholder imidlertid ikke informasjon om bydel, kun andre kretser. Se Grunndata modellene for detaljer.
