### ISSUE TITLE
Høring R4-basis: Pseudonym-id

### ISSUE THREAD

**Issue by oaassv** [HL7Norway/basisprofiler-r4#12]
Innspill fra Gustav Bellika på å vurdere å legge til slice også for pseudonym-id som er viktig for å kunne hente ut informasjon i forskningsøyemed. Er dette kandidat for basisprofil, eller heller nasjonale profiler for forskning? 

"Her er et forsøk på å spesifisere informasjonen vi trenger for å kunne pseudonymisere pasienter og helsearbeidere i data som gjenbrukes. 
For å ivareta pseudonymisering av pasientidentifikatorer og helsearbeidere bruker vi 2 variable.
Pseudonym-id og prosjekt-id. 
 
Pseudonym-id er i dag en 256 bit hash av SHA256(Person-nummer | nøkkelstreng ). Nøkkelstreng er en tilfeldig tekst-streng som er tilknyttet et prosjekt, identifisert med prosjekt-id variabelen. Denne nøkkelstrengen deles av alle institusjoner som er med i et prosjekt, men må ikke deles med andre som ikke er del av prosjektet (dvs. må lagres på EPJ server). Pseudonym-id vil derfor være globalt unik.
 
Siden vår Pseudonym-id kan øke i fremtiden (overgang til SHA512eller andre hashing algoritmer) er kanskje det beste å benytte en variable lengde datatype for denne  variabelen?
 
Prosjekt-id kan være en uuid, ala:
c81cda79-2969-4b78-a4d3-d8e44696a62d
b8fc2dd6-b5fe-44e6-8085-bfef2a46b1b0"

øyvind

**Comment by thomiz** [comment]
Jeg vil foreslå å ha pseudonym-id som en del av en nasjonal profil for forskning.
- den har ingen funksjon i behandlingsøyemed
- gjelder et fåtall konkrete brukertilfelle og no-basis mener jeg skal være mer generell
