### ISSUE TITLE
Is there a Value set available for urn:oid:2.16.578.1.12.4.1.1.9060 Value set binding in the Repo.

### ISSUE THREAD

**Issue by kalleo1996** [HL7Norway/basisprofiler-r4#121]
I would like to know where I can find the definition or XML file for the value set with the URN: "urn:oid:2.16.578.1.12.4.1.1.9060". The structure definition "http://hl7.no/fhir/StructureDefinition/no-basis-Practitioner" includes a value set binding, and although I know it is accessible on volven.no, I am wondering if there should be a dedicated value set created in the repository for it.
`
 {
        "id": "Practitioner.qualification.code.coding:healthPersonnellCategory",
        "path": "Practitioner.qualification.code.coding",
        "sliceName": "healthPersonnellCategory",
        "short": "The health care personnel category",
        "definition": "Category of health care personnel authorization according to Helsepersonnelloven §48",
        "binding": {
          "strength": "preferred",
          "valueSet": "urn:oid:2.16.578.1.12.4.1.1.9060"
        }
      },
      {
        "id": "Practitioner.qualification.code.coding:healthPersonnellCategory.system",
        "path": "Practitioner.qualification.code.coding.system",
        "short": "Identification of the CodeSystem 9060 on Volven",
        "definition": "Identification of the CodeSystem Kategori helsepersonell (OID=9060) used to describe the category of authorized health care personnel",
        "min": 1,
        "fixedUri": "urn:oid:2.16.578.1.12.4.1.1.9060"
      },`

**Comment by cgerno** [comment]
Check that:
https://volven.no/produkt.asp?id=499915&catID=3&subID=8

**Comment by kalleo1996** [comment]
Can we have same oid for valueset and the codesystem ? I mean, should we not create a valueset Like this in the repo .
{
  "resourceType": "ValueSet",
  "status": "draft",
  "name": "HealthPersonallCategoryValueset",
  "id": "HealthPersonallCategoryValueset",
  "title": "HealthPersonallCategoryValueset",
  "description": "Have volven codesystems and rest of the namesystem",
  "version": "1.0.0",
  "url": "http://example/fhir/ValueSet/HealthPersonallCategoryValueset",
  "meta": {
    "lastUpdated": "2021-03-17T00:00:00+00:00",
    "profile": [
      "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
    ]
  },
  "extension": [
    {
      "url": "http://hl7.org/fhir/StructureDefinition/structuredefinition-wg",
      "valueCode": "oo"
    },
    {
      "url": "http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status",
      "valueCode": "draft"
    },
    {
      "url": "http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm",
      "valueInteger": 1
    }
  ],
 
  
  "compose": {
    "include": [
      {
        "system": "urn:oid:2.16.578.1.12.4.1.1.9060",
        "concept": [
          {
            "code": "AA",
            "display": "Ambulansearbeider"
          },
          {
            "code": "AT",
            "display": "Apotektekniker"
          },
          {
            "code": "AU",
            "display": "Audiograf"
          },
          {
            "code": "BI",
            "display": "Bioingeniør"
          },
          {
            "code": "ET",
            "display": "Ergoterapeut"
          },
          {
            "code": "FA1",
            "display": "Provisorfarmasøyt"
          },
          {
            "code": "FA2",
            "display": "Reseptarfarmasøyt"
          },
          {
            "code": "FB",
            "display": "Fiskehelsebiolog"
          },
          {
            "code": "FO",
            "display": "Fotterapeut"
          },
          {
            "code": "FT",
            "display": "Fysioterapeut"
          },
          {
            "code": "HE",
            "display": "Helsesekretær"
          },
          {
            "code": "HF",
            "display": "Helsefagarbeider"
          },
          {
            "code": "HP",
            "display": "Hjelpepleier"
          },
          {
            "code": "JO",
            "display": "Jordmor"
          },
          {
            "code": "KE",
            "display": "Klinisk ernæringsfysiolog"
          },
          {
            "code": "KI",
            "display": "Kiropraktor"
          },
          {
            "code": "LE",
            "display": "Lege"
          },
          {
            "code": "NP",
            "display": "Naprapat"
          },
          {
            "code": "OA",
            "display": "Omsorgsarbeider"
          },
          {
            "code": "OI",
            "display": "Ortopediingeniør"
          },
          {
            "code": "OP",
            "display": "Optiker"
          },
          {
            "code": "OR",
            "display": "Ortoptist"
          },
          {
            "code": "OS",
            "display": "Osteopat"
          },
          {
            "code": "PE",
            "display": "Perfusjonist"
          },
          {
            "code": "PM",
            "display": "Paramedisiner"
          },
          {
            "code": "PS",
            "display": "Psykolog"
          },
          {
            "code": "RA",
            "display": "Radiograf"
          },
          {
            "code": "SP",
            "display": "Sykepleier"
          },
          {
            "code": "TH",
            "display": "Tannhelsesekretær"
          },
          {
            "code": "TL",
            "display": "Tannlege"
          },
          {
            "code": "TP",
            "display": "Tannpleier"
          },
          {
            "code": "TT",
            "display": "Tanntekniker"
          },
          {
            "code": "VE",
            "display": "Veterinær"
          },
          {
            "code": "VP",
            "display": "Vernepleier"
          },
          {
            "code": "XX",
            "display": "Ukjent/uspesifisert"
          },
          {
            "code": "MT",
            "display": "Manuellterapeut"
          }
        ]
      }
    ]
  }
}

**Comment by thomiz** [comment]
We have decided not to make FHIR valueset or codesystem resources as part of the no-basis for the volven codesystems.

This thread explains why:
[https://github.com/HL7Norway/basisprofiler-r4/issues/61](issue #61)

However this issue should be revisited probably.

**Comment by rockphotog** [comment]
@kalleo1996 We do have 9060 as a Code System in this IG, but not as Value Set, unfortunately.  

https://hl7norway.github.io/kodeverk/currentbuild/CodeSystem-no-kodeverk-9060.codesystem.html 
Repo: https://github.com/HL7Norway/kodeverk 

Most, if not all, code systems in Volven have a practical 1:1 between CS and VS, so they _should_ be autogenerated, and named thereafter.

**Comment by thomiz** [comment]
Closed after review.
