### ISSUE TITLE
Publisere 2.2.0 versjon - registry

### ISSUE THREAD

**Issue by thomiz** [HL7Norway/basisprofiler-r4#127]
Det kommer opp gammel versjon i pakksøket på HL7 pakkeregistry:
* registry.fhir.org

* Sjekk med Firely om det er noen grunn til dette.

* Oppdatere fhir.org/guides/registry med ny IG.

* Pluss: lage et klassediagram til Guiden for å vise Appointment med extensions.

**Comment by rockphotog** [comment]
Mulig registry.fhir.org henter noe fra repo'et til Grahame, som jeg la noe inn i for lenge siden - altså en manuell prosess?

**Comment by thomiz** [comment]
Det var en feil på SIMPLIFIER som gjorde dette. Firely har fikset det nå:  
[no-basis i registry](https://registry.fhir.org/results?query=%22no-basis%22&latestFilter=true)
