### ISSUE TITLE
Noen utfordring med bruk av kommunikasjonspart-organisation ([ERROR] Profile 'http://hl7.no/fhir/StructureDefinition/kommunikasjonspart-Organization' does not include a snapshot. )

### ISSUE THREAD

**Issue by helgaarm** [HL7Norway/basisprofiler-r4#129]
Det er noe som har hent med kommunikasjonspart-organization. Profilen validerer ikke når den brukes i instancer
(https://simplifier.net/hl7norwayno-basis/kommunikasjonspart-organization)

**Comment by thomiz** [comment]
Den er vel ikke med i no-basis pakken heller, for den er draft?
Vi bør antakelig fjerne den fra no-basis repo siden vi aldri kom i mål med den.
