### ISSUE TITLE
Feil i invariant app-4 i no-basis-appointment

### ISSUE THREAD

**Issue by helgaarm** [HL7Norway/basisprofiler-r4#132]
Invarianten er i dag som følger: 

Cancelation reason is only used for appointments that have been cancelled, or no-show: 
`Appointment.cancelationReason.exists() implies (Appointment.status='no-show' or Appointment.status='cancelled')`

Feilen er at **no-show** er status som ikke finnes det skulle vært **noshow**

**Comment by thomiz** [comment]
Får vi en fiks på denne sammen med AuditEvent (2.3.0) iløpet av et par uker? @helgaarm

**Comment by helgaarm** [comment]
Ja - håper jeg kan legge det inn ila nestes uke @thomiz

**Comment by helgaarm** [comment]
Jeg har ikke oppdatert versjon på structureDefinition - blir den oppdatert automatisk ved bygg?
