### ISSUE TITLE
Feil i Title for ut videlsene NoBasisVirtualService og NoBasisRelatedpersonPersonReference

### ISSUE THREAD

**Issue by thomiz** [HL7Norway/basisprofiler-r4#134]
[NoBasisRelatedpersonPersonReference](https://simplifier.net/hl7norwayno-basis/nobasisrelatedpersonpersonreference) - mangler title (husk lowercase)  

[NoBasisVirtualService](https://simplifier.net/HL7Norwayno-basis/NoBasisVirtualService/~xml) - har feil i title (bruker camelcase, skal ha lowercase)

**Comment by helgaarm** [comment]
Kort spørsmål før jeg legger in fix - branch. Skal jeg oppdatere versjon manuelt?

**Comment by thomiz** [comment]
Ja @helgaarm det må gjøres manuelt, men siden AuditEvent blir domeneprofil, så blir dette 2.2.1 versjon. Jeg skal fikse nytt label.
