### ISSUE TITLE
Trenger bedre kodesystem (verdisett) - PractitionerRole.code:functions.coding.system

### ISSUE THREAD

**Issue by rockphotog** [HL7Norway/basisprofiler-r4#135]
Kodeverket som ligger der i dag ( https://volven.no/produkt.asp?id=520792&catID=3&subID=8 ) er for spisset - det er behov for et bredere, spesielt med tanke på rolle overnfor pasient. Tenker på bl.a. kommunale tjenester, som sykepleier, hjemmehjelp, helsefagarbeider, etc.

Use case for prosjekt [LMDI](https://github.com/HL7Norway/LMDI) trenger spesielt verdisett for roller for som administrerer legemiddel, og må ant. også inneholde "pårørende, pasienten selv, etc". 

(ping @lisaFHI )

**Comment by thomiz** [comment]
Dette er en åpen slice i no-basis, det betyr at ethvert annet verdisett kan benyttes der dette ikke er dekkende. 

Jeg er usikker på om rollen til pårørende skal være med her fordi: 
> The Practitioner resource is used for anyone involved in the provision of care or services to a Patient associated with an organization. The RelatedPerson resource is used for anyone involved in the care for a patient, typically having a personal *relationship *or non-healthcare-specific professional relationship to the patient.

**Comment by rockphotog** [comment]
Det er riktig at det beste er å bare referere til Patient, RelatedPerson - men hadde vært så digg å bare kode det. Fikser det selv. 

Men kodeverket i no-basis-practitionerRole er uansett et litt merkelig og lite dekkende utvalg, tar gjerne en runde på det.  Men spørsmålet er vel om vi trenger noe "kommune-FHIR-prosjekt" på banen.

**Comment by thomiz** [comment]
Jeg tror vi venter med denne til vi har konkrete forslag til flere kodeverk som bør nevnes i no-basis for dette elementet.

**Comment by rockphotog** [comment]
Ja, men det var egentlig det jeg ønsket - at det ble utviklet konkrete kodesett, typ av Helsedirektoratet. Ikke spille inn noe som ikke finnes til no-basis... :-) Men det bør kanskje adresseres Hdir direkte.

**Comment by thomiz** [comment]
Absolutt, vi tar ikke utvikling av nye kodeverk som issue til nobasis
