### ISSUE TITLE
Høring R4-basis: Kommentarer fra "SAFEST-Gjennomføring"-prosjektet og Statens Legemiddelverk på Medication og Substance

### ISSUE THREAD

**Issue by stinejohans1** [HL7Norway/basisprofiler-r4#15]
Hei, sitter som konsulent hos Statens Legemiddelverk hvor jeg er involvert i "SAFEST gjennomføring"-prosjektet. Vi skal jobbe mye med FHIR og profiler fremover og har noen kommentarer til ressursene Medication og Substance, som potensielt er aktuelle for oss å bruke i SAFEST-løsningen;

På generelt grunnlag synes vi det er noe manglende beskrivelser for hva nye felter er og betyr. Det hadde eksempelvis være fint med en kommentar til "FEST-Medication" og "FEST-form" hva tanken er at man skal legge inn. Steder hvor man bruker OID i system-feltet kan også med fordel forklares med en kort beskrivelse av hvor kodeverket eksisterer.

Ingen av url'ene til E-helse som ligger definert under System for Coding fungerer, bør legge inn nye?

Videre tenker vi at det kanskje ikke er hensiktsmessig å referere til et system, men heller referere til instansen som eier kodeverk. FEST skal på sikt erstattes, ville det vært bedre å referere til SLV, i stedet for systemet som per dags dato brukes for å distribuere kodene? 

Volven er også brukt flere steder for kodeverk, Vovlen skal jo bort, er det tiltenkt å lage nye versjoner av profilene når det skjer?

_Substance_

- Hva refereres det til i FEST-Substance?
    - Fullstendig substans og/eller terapeutisk virkestoff?

_Medication_
- Har vi forstått det riktig at FEST-Medication referes til PakningsID fra M30?
- PerscriptionGroup
    - IDMP bruker begrepet LegalStatusOfSupply, bruke samme ordbruken?

Vi står per i dag på litt tynn is og kjenner lite til bakgrunnen for de valgene som er tatt til nå. Vi stiller gjerne til samtaler for å diskutere dette. Det kan da tenkes at høringsfristen 2. september er litt kort tid til, vil det være mulig å utsette fristen for akkurat disse to profilene?

**Comment by rockphotog** [comment]
Hei

Vi kan gjerne ta en prat. 2. september-fristen er ute, men vi må skru på profilene til alle er fornøyd. 

Jeg har ikke jobbet direkte med disse, men det har @olemartinwinnem og @daghammer . 

Jeg tror at bakgrunnen for å peke på div "FEST-id" er å få kompabilitet med slik de benyttes i dag, spesielt i sammenheng med eResept. Når IDMP foreligger må det legges inn støtte for det i profilene. Jeg regner med at en overgang fra "FEST-id" og avvikling av M30 over til ny FHIR-API for (SA)FEST vil gå over tid, så disse må kanskje leve parallelt en god stund.

**Comment by rockphotog** [comment]
Kodeverk på Volven: Per nå er OID'er og URL til Volven "non-resolvable", dvs. det er egentlig kun en identifikator (URI). Det jobbes med at alle administrative kodeverk på Volven skal kunne publiseres som CodeSystem/ValueSet fra den nye løsningen for kodeverk, HealthTerm. Når dette er klart kjenner jeg ikke til. 

"FEST-medication", "FEST-form", etc bør som du sier antageligvis peke på SLV, og her er det mulig vi bør bruke (instans av) NamingSystem-ressursen, i tillegg til å gjøre dokumentasjonen bedre.

**Comment by olemartinwinnem** [comment]
Hvis du med terapautisk virkestoff mener legemiddel med ATC kode så er det representert som medication. Substance er ment å ivareta virkestoff fra virkestoff katalogen i FEST, også referanse mellom dem. 

FEST-Medication peker på alle typer legemiddel i FEST, ikke bare pakning. Altså legemiddelvirkestoff, legemiddelpakning og legemiddelmerkevare. 

Enig i at vi burde ha en entydig måte å referere kodeverk.

**Comment by oaassv** [comment]
Forklaring på attributtene på Medication-ressursene legges inn, inkl referanse til foreslåtte begreper fra IDMP.

**Comment by rockphotog** [comment]
Det er viktig at evt. IDMP-attributter (f.eks. MPID) er identiske med andre (internasjonale) IF'er. Dreier seg vel stort sett om å ha riktig namespace/system (navn på slice er vel mest informativt?)

**Comment by rockphotog** [comment]
@stinejohans1 Har opprettet et område for [SAFEST](https://github.com/HL7Norway/SAFEST), så ses vi etter høstferien!

**Comment by stinejohans1** [comment]
@rockphotog Takk. 

Ang. de andre kommentarene om utbedring av forklaringer og bruk av IDMP-begreper, så høres det bra ut.

**Comment by oaassv** [comment]
@stinejohans1 
Vi har laget en oppdatert versjon av medikasjonsressursene basert på innspillene fra SLV. Har dere mulighet gå gjennom og kvalitetssikre at endringene er ok i løpet av de neste dagene?

**Comment by stinejohans1** [comment]
@oaassv for min del ser det bra ut, pga. ferieavvikling hos SLV har ikke alle fått sett på det, men jeg antar det er greit, og denne kan lukkes.

**Comment by oaassv** [comment]
Den er god, da lukker jeg. Men la oss vite hvis dere eventuelt ser flere ting som bør justeres.
