### ISSUE TITLE
Behov for basisprofil: Encounter

### ISSUE THREAD

**Issue by rockphotog** [HL7Norway/basisprofiler-r4#2]
Del av minimumsett for SMART on FHIR for EPJ-API. 
Pri start 2019 @oaassv

**Comment by rockphotog** [comment]
Brukes Encounter i førerrett, @kennethmyhra ?

**Comment by kennethmyhra** [comment]
Nei, Encounter brukes ikke i Førerrett slik det er spesifisert i dag.

**Comment by rockphotog** [comment]
Da lukker jeg denne, så lager vi ny issue når det er aktuelt igjen.

**Comment by kennethmyhra** [comment]
Tja, gjør ingenting om det ligger høyt på agendaen, Encounter burde være en tidlig kandidat.
