### ISSUE TITLE
Valideringsproblemer XDS

### ISSUE THREAD

**Issue by rockphotog** [HL7Norway/basisprofiler-r4#23]
En del av våre profiler peker på lokale XSD'er, kan det skape problemer?

Eksempel fra [no-basis-bydelsnummer.namingsystem.xml](https://github.com/HL7Norway/basisprofiler-r4/blob/namingsystem-fest-id/NamingSystem/no-basis-bydelsnummer.namingsystem.xml)

`<NamingSystem xmlns="http://hl7.org/fhir" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://hl7.org/fhir file:///C:/GitRepo/R4/fhir-all-xsd/fhir-single.xsd">`

Jeg byttet forøvrig ut `file:///C:/GitRepo/R4/fhir-all-xsd/fhir-single.xsd` med `https://www.hl7.org/fhir/fhir-base.xsd` på [validatoren her](http://tx.fhir.org/r4) uten å komme videre.

**Comment by thomiz** [comment]
Jeg tror ikke de lokale profilene lager problemer, men helt sikker kan man jo ikke være. Antakelig best å ta det bort på det som ligger på Git.

For validering mot xml-skjema (i XMLspy) er absolutt fil-referanse til fhir-single.xsd det enkleste å benytte.
For validering mot FHIR spekk med [validatoren ](https://wiki.hl7.org/Using_the_FHIR_Validator) eller på SIMPLIFIER trengs ikke annet enn namespace, ingen xsi:schemaLocation eller xmlns:xsi er nødvendig for den biten.

**Comment by thomiz** [comment]
Rettelse  [validatoren](https://wiki.hl7.org/Using_the_FHIR_Validator) klager på disse filreferansene. Den vil hverken ha xsi:schemaLocation eller xmlns:xsi, litt rart egentlig.

**Comment by thomiz** [comment]
Det skal være rettet i siste versjon av no-basis
