### ISSUE TITLE
Vurdere kardinalitet HumanName.given

### ISSUE THREAD

**Issue by kennethmyhra** [HL7Norway/basisprofiler-r4#27]
Kardinaliteten for HumanName.given er endret fra 0..* til 0..1 og betyr at basisprofilene har et avvik fra basespesifikasjonen.

Mitt forslag er å endre dette tilbake til 0..* da jeg er bekymret for at det kan skape problemer for interoperabilitet der man kjøper systemer som har implementert given i henhold til basespesifikasjonen eller på tvers av landegrenser.

**Comment by thomiz** [comment]
Jeg er tildels enig. Det trenger ikke bli ett problem (avhengig av implementasjon), men det kan bli det. Norske navn skal etter navneloven ha så mange fornavn man ønsker. Skatteetaten har innført en praksis hvor alle navn ligger i en streng i Personnavnet, dette er også nedfelt i felles informasjonsmodell for Person https://www.difi.no/fagomrader-og-tjenester/digitalisering-og-samordning/nasjonal-arkitektur/informasjonsforvaltning/person-og-enhet-felles-informasjonsmodell
 
Ved bruk av FHIR er det vanlig å ha flere elementer av given for å angi flere fornavn, men det vi da får fra folkeregisteret vil være en streng med alle fornavnene. Men selv om Skatteetaten eksponerer fornavnene slik betyr ikke det at den begrensningen trenger å komme i no-basis. Vi kan endre det på no-basis-Person/Patient og kun nedfelle dette kravet i gd-Person/Patient.

**Comment by kennethmyhra** [comment]
Opprettet PR #28

**Comment by thomiz** [comment]
Jeg mener vi trenger litt mer ofattende beslutningsprosess rundt denne endringen @kennethmyhra 
Kanskje noe formalisert opplegg i TSK @oaassv @rockphotog ?

**Comment by kennethmyhra** [comment]
Jepp, enig @thomiz

**Comment by rockphotog** [comment]
Ja. Nå som basisprofiler havner i referansekatalogen må vi lage ferdig retningslinjer for hva som er innafor av endringer. F.eks. at versjon 1.0.X er bugfikser som ikke krever noe særlig i forvaltning, mens 1.X.0 er større og ikke automagisk blir en del av referansekatalogen. Endring av kardinalitet, selv om det er å løse opp, er kanskje borderline mellom disse to.

**Comment by kennethmyhra** [comment]
Dette vil jeg kalle en breaking change og dermed en major version endring. Vet vi om prosjekter utenfor direktoratet har gått i produksjon med disse? Jeg kunne godt tenkt meg at vi diskuterer denne endringen før EPJ-ene begynner implementasjon av HelseAPI i forbindelse med Førerrett.

**Comment by oaassv** [comment]
TSK behandlet denne fredag. TSK er positive til å endre, men vil gjerne ta en runde på de implementeringsmessige konsekvensene av endringene.

**Comment by kennethmyhra** [comment]
@oaassv Kan du kalle inn til et internt møte?

**Comment by oaassv** [comment]
@kennethmyhra - tok en lunsjrunde på dette med @thomiz og @rockphotog. Konklusjonen er slik jeg oppfatter det at vi bør endre basisprofilen. Vi har ikke etablert forvaltnings- /endringsprosesser, og forslaget var at det ikke haster, og at vi kan bruke endringen som et eksempel i utarbeidelse av forvaltningsprosessene. Det vil si at vi oppdaterer i løpet av våren. Kan sette opp endringsprosesser som team på neste TSK-møte. Høres det greit ut?

**Comment by kennethmyhra** [comment]
@oaassv Det er greit at du setter det opp som tema på neste møte. I praksis betyr det at jeg, inntil endringen kommer inn i basisprofilene, endrer Patient og Practitioner profilene i HelseAPI til å ikke arve fra basisprofilene, det er eneste måten å unngå nåværende kardinalitet.

**Comment by rockphotog** [comment]
Burde denne tas som ekstra punkt på workshop? @oaassv

**Comment by rockphotog** [comment]
Vi fikk diskutert det kort på workshop i dag - stemningen var vel tommel opp for 0..1 -> 0..*.

**Comment by rockphotog** [comment]
For the record for senere: Å løse opp en kardinalitet på denne måten, også gå fra f.eks. 1..1 til 0..1 anses som breaking change når vi kommer til implementerte systemer.

**Comment by oaassv** [comment]
Settes på agenda på møte i TSK 7.januar.

**Comment by thomiz** [comment]
Gikk igjennom TSK uten endringer. @kennethmyhra ordner opp i merge conflicts (snapshot er tatt bort siden sist). Oppdatere versjonsnummer for no-basis-Humanname til 2.0.15 så legger jeg det inn i samme pakke som #70 #42 og eventuelt #34

**Comment by kennethmyhra** [comment]
@thomiz konflikt, versjonnummer og merge tilbake til master er utført

**Comment by thomiz** [comment]
Mottatt.
