### ISSUE TITLE
Update text in IG describing HERid in Organization and Practitioner

### ISSUE THREAD

**Issue by thomiz** [HL7Norway/basisprofiler-r4#32]
Update text on HERid in Organization and Practitioner, the text is not clear and easy to misunderstand.
The plan is to use Organization and not the HCS resource for kommunikasjonspart.
I will post a proposal soon, i guess we can make clarifications in the IG text without bumping the version number. 
@rockphotog @oaassv

**Comment by oaassv** [comment]
Topp!     På tirsdag 4. februar 2020, 10:12:22 CET skrev Thomas Tveit Rosenlund <notifications@github.com> følgende:  
 
 
Update text on HERid in Organization and Practitioner, the text is not clear and easy to misunderstand.
The plan is to use Organization and not the HCS resource for kommunikasjonspart.
I will post a proposal soon, i guess we can make clarifications in the IG text without bunping the version number.
@rockphotog @oaassv

**Comment by thomiz** [comment]
Proposal for new text on the IG pages describing HERid:
```
A special note on the use of HERid in Organization resources instances

Organizations that participates in message based electronic communication in Norway 
uses a special identifier called HERid to identify the communication parties (e.g. 
"kommunikasjonspart") of the organization. The HERid's are not meant to be recorded 
directly on the no-basis-Organization (or derived profiles) instance resources representing 
information about the Organization. Information about the communication parties of the 
Organization are to be registered on a special kind of organization instance developed for this 
purpose, the suggested name of such a profile is "kommunikasjonspart-Organization" 
and is to be developed in a future release of the norwegian FHIR framework.
```

Please review @oaassv @rockphotog @AnnebethA

**Comment by thomiz** [comment]
@rockphotog @oaassv @AnnebethA Still needs review on this one.

**Comment by thomiz** [comment]
Vi gjør dette veldig enkelt:
The HERid SHALL not be assigned on the Organizational level. The Organizations registered in adresseregisteret uses the HERid for message based addressing.

**Comment by rockphotog** [comment]
Enig, effektuere?

Er master for basis-IG Simplifier? Vi må skrive dette på under Best Practice wiki også så det ikke forsvinner.

**Comment by thomiz** [comment]
Fikset på Organization og Practitioner.

Skulle vi hatt samme tekst på PractitionerRole?

**Comment by rockphotog** [comment]
Tror ikke det er nødvendig - dog usikker. Det er kanskje ikke nødvendig å ta alle sorger på forskudd selv om presisering er bra. 

Et generelt problem er at _noen_ mener at hvis noe ikke eksplisitt forbudt i en standard så er det lov. Det vil jo gjøre alle standarder umulig store. Dette reguleres vanligvis av en god beskrivelse av anvendelse, men for basisprofiler har vi jo ikke det i samme grad.

**Comment by thomiz** [comment]
Lukker denne siden oppdateringen er gjennomført i [Implementasjonsguiden](https://simplifier.net/guide/no-basis-entities-individuals/introduction)
