### ISSUE TITLE
Add code to the  no-basis-parental-responsibility Code System

### ISSUE THREAD

**Issue by thomiz** [HL7Norway/basisprofiler-r4#33]
https://simplifier.net/HL7Norwayno-basis/no-basis-parental-responsibility

Can we add the code "ukjent" to this CodeSystem with a bugfix release (2.0.12)?
Turns out Skatteetaten utilizes this code from the FREG service.
@kennethmyhra @rockphotog @oaassv

**Comment by oaassv** [comment]
Hei, det bør vi vel kunne gjøre. Regner med at ingen har implementert denne (bortsett eventuelt fra grunndata)?

**Comment by thomiz** [comment]
Oppdatert i branch https://github.com/HL7Norway/basisprofiler-r4/tree/add-code-value-ukjent
