### ISSUE TITLE
no-basis-HumanName R4

### ISSUE THREAD

**Issue by rockphotog** [HL7Norway/basisprofiler-r4#4]
Kardinaliteter på navn på løses opp til 0..(x), ikke 1..(x). 

Diskutert/foreslått på workshop Gardermoen 2019-02-05.

**Comment by rockphotog** [comment]
Profilerte kardinaliteter fjernes.

**Comment by thomiz** [comment]
Fikset i R4 versjon. Sjekket inn på Git.
