### ISSUE TITLE
RelatedPerson.patient reference

### ISSUE THREAD

**Issue by thomiz** [HL7Norway/basisprofiler-r4#42]
Feilen går ut på at no-basis innfører en referanse til no-basis-Person i RelatedPerson.patient referansen.

Forslaget til endring:
Fjerne no-basis-Person referansen fra RelatedPerson.patient elementet, da denne strider mot hva man kan gjøre med profilering i HL7 FHIR. Dette skaper igjen problemer ved implementasjon hvor søk på no-basis-Person referansene ikke fungerer. Ivareta behovet for no-basis-Person referanser gjennom en extension:
- Konstruere no-basis-Person referanse i extension (0..1) som kan brukes i no-basis-RelatedPerson
- Ikke legge inn personreferansen i RelatedPerson men la dette være opp til implementasjoner som har behov for slike relasjoner
- Rådgi om at Patient referansen må være en identifier/navn (siden man ved relasjoner til en person ikke har literal reference)

I tillegg foreslås det: 
Jobbe for endringer i RelatedPerson i HL7 International
- Forslaget i no-basis bryter litt med semantikken i RelatedPerson som lyder «person that is involved in the care for a patient”
- Det er også diskuterte et alternativ med endring i no-basis-Person for å håndtere relasjoner mellom personer i Person ressursen. Forslaget går uansett ut på å samle alle relasjoner (pasient og person relasjoner) i RelatedPerson så det skal være enklere å finne relasjoner, enn om noen ligger i Person og noen ligger i RelatedPerson

**Comment by oaassv** [comment]
Settes på agenda på møte i TSK 7.januar.

**Comment by thomiz** [comment]
Diskutert i TSK 2021-01-08

Enig om å gjennomføre endringen
- Fjerne no-basis-Person referansen fra RelatedPerson.patient elementet
- Opprette extension for no-basis-Person referanse i extension (0..1) som kan brukes i no-basis-RelatedPerson
   - Ikke legge inn personreferansen i RelatedPerson men la dette være opp til implementasjoner som har behov for slike relasjoner
   - Dokumentere (i extension) at både logisk og literal referanse bør oppgis i extension (for at søk på identifier skal fungere)
- Dokumentere at Patient referansen må være en identifier/navn (siden man ved relasjoner til en person ikke har literal reference)
