### ISSUE TITLE
Add SearchParameter/no-basis-middlename to the normative no-basis

### ISSUE THREAD

**Issue by thomiz** [HL7Norway/basisprofiler-r4#43]
Propose to make the status of SearchParameter definition for no-basis-middlename "active" and update the no-basis package to include the no-basis-middlename SearchParameter definition.
https://simplifier.net/hl7norwayno-basis/no-basis-middlename

Reason: The search parameter have been tested by the Grunndata R4 implementation and it works as expected. I believe other projects have used it as well @kennethmyhra ?

Changes needed:
Update to ImplementationGuide for no-basis to include a page describing the SearchParameter
Update the SearchParameter to include version information and status=active
Update the package to version 2.0.14 and inlude all active resources

**Comment by kennethmyhra** [comment]
Søkeparameteret er ikke nevnt i dagens versjon av HelseAPI

**Comment by rockphotog** [comment]
Søkeparameteret kan være kjekt å ha, men jeg tror ikke jeg vil anbefale det å være _mandatory by default_ - usikker på behovet. Erfaringer fra f.eks. eResept viser at typisk søk på mellomnavn er vanskelig, man ønsker stort sett å gjøre søk på fritekst, så på etternavn/fornavn. Grunndata har klart andre behov. Uansett, ingenting er tvang i basisprofiler, spesielt ikke søkeparametere.

**Comment by thomiz** [comment]
@rockphotog Forslaget går ikke ut på å gjøre støtten mandatory, men å gjøre søkeparameteret tilgjengelig i no-basis pakken så det enklest mulig kan tas i bruk for å søke etter verdier i no-basis-middlename extension. Er litt usikker på hva det egentlig betyr å gjøre søkeparameteret "normativt", det betyr ihvertfall ikke at man må bruke det. Jeg tror heller ikke det betyr at man må støtte det i løsningen man utvikles, for det kan styres i CapabilityStatement. De som ikke er fornøyd med søkeparameteret og måten det fungerer kan jo lage et annet søkeparameter med ett annet navn og benytte det?

Hva active og normativt betyr for søkeparameter, operation og extension definisjoner i no-basis må vi kanskje beskrive nærmere?

Vi har ett eksempel på en extension som ikke er tatt inn i profilene, men som ligger som active, er beskrevet i IG og derfor er normativt men frivillig å benytte (jamfør åpen profilering):
https://simplifier.net/guide/no-basis-Entities-Individuals/no-basis-person-citizenship

Denne er vel tenkt som et tilbud, hvis du trenger statsborgerskap på person. Tenkte egentlig at alle søkeparametere vil fungere på samme vis, men at de bør være active, være beskrevet i IG og normative.

**Comment by rockphotog** [comment]
Da tar vi det med 👍

**Comment by thomiz** [comment]
# Forslag til definisjoner

**Extension:**  
No-basis-Extensions are typically not mandatory. The extensions represents a normative way of representing a specific information structure to cover a common national use-case for information interoperability and aggregation.

**SearchParameter:**  
No-basis-SearchParameters are typically not mandatory. Implementations should state the support of the SearchParameter in the CapabilityStatement.

**OperationDefinition:**  
No-basis-OperationDefiniton are typically not mandatory. Implementations should state the support of the OperationDefinition in the CapabilityStatement.
