### ISSUE TITLE
no-basis-Composition

### ISSUE THREAD

**Issue by rockphotog** [HL7Norway/basisprofiler-r4#48]
Dette er den "offisielle" tråden for basisprofil Composition. 

Jeg har opprettet prosjekt for basisprofiljobbing i 2020 (og begynner snart på 2021), og trenger dermed denne. 

Bruk denne for generell diskusjon, kommentarer og oppfølging. Spesifikke forslag, bugs etc. kan opprettes som egne issues.

**Comment by rockphotog** [comment]
Diskuteres på @HL7Norway/tsk 25.9.2020.

**Comment by rockphotog** [comment]
Fra TSK: Sendes ut på høring fra HL7 Norge.

**Comment by oaassv** [comment]
Ingen kommentarer mottatt i løpet av høring.
