### ISSUE TITLE
Dokumenttype (DocumentReference, Composition)

### ISSUE THREAD

**Issue by rockphotog** [HL7Norway/basisprofiler-r4#52]
Diskuteres TSK 25.9.2020

Gjelder i første omgang no-basis-DocumentReferece.type og no-basis-Composition.type

Valg av kodeverk:
- Volven
- SNOMED CT
- LOINC

Vi går for VOLVEN inntil videre.

**Comment by rockphotog** [comment]
Volven OID = 9602
https://volven.no/produkt.asp?id=424810&catID=3&subID=8

**Comment by rockphotog** [comment]
Fra TSK: Sendes ut på høring fra HL7 Norge - se #48 og #49 .

**Comment by thomiz** [comment]
Ingen invendinger fra høringsprosessen.

**Comment by thomiz** [comment]
Lager du en Pullrequest for å gjøre disse profilene som active @kennethmyhra 
Kan du samtidig gjøre alle profilene/extensions som differential?

**Comment by kennethmyhra** [comment]
@thomiz PR laget for DocumentReference og Composition.

Med alle profilene/extensions, tenker du på hele repoet?

**Comment by kennethmyhra** [comment]
Fjernet også alle Snapshot components i StructureDefinition #60

**Comment by thomiz** [comment]
Jeg tenker i utgangspunkt på alle StructureDefinitions. Tror ikke vi har snapshot's noe annet sted.
