### ISSUE TITLE
Masse rart havner på Simplifier

### ISSUE THREAD

**Issue by rockphotog** [HL7Norway/basisprofiler-r4#58]
Se f.eks. https://simplifier.net/hl7norwayno-basis/d

Må vi ta en titt på .gitignore?

**Comment by rockphotog** [comment]
Eller er det bare jeg som er dum - er dette genererte filer for IG'en?

https://simplifier.net/HL7Norwayno-basis/~resources?category=Text&fhirVersion=R4&sortBy=RankScore_desc

**Comment by thomiz** [comment]
Det er nok i hovedsak genererte filer fra SIMPLIFIER IG, det kan jo hende akkurat den "d" fila ikke har noe der å gjøre. Ingenting av dette ligger i Github repoet, og de skal heller ikke være der.

**Comment by rockphotog** [comment]
Så dette er kanskje en henvendelse til Firely om det kan være mulig å skjule IG-genererte filer? Det gjør jo ikke noe direkte skade, men det ser veldig rotete ut når man ser på alle filene i prosjektet.

**Comment by thomiz** [comment]
Lukker denne. Vi må uansett gjøre en totalvurdering når vi ser på publiseringsverktøy.
