### ISSUE TITLE
Mangler IG for no-basis-Composition og no-basis-DocumentReference profilene

### ISSUE THREAD

**Issue by thomiz** [HL7Norway/basisprofiler-r4#64]
Disse nye profilene må beskrives i IG for no-basis.

**Comment by thomiz** [comment]
Vi må ha disse sidene opp ASAP! @kennethmyhra @rockphotog

**Comment by kennethmyhra** [comment]
@thomiz Hva må gjøres for at sidene skal komme opp? Har ingen erfaring med IG-formatet.

Ser at det ligger overstyring på noen av kommentarene i DocumentReference profilen som betyr at vi har lagt inn egne kommentarer/dokumentasjon. Utover det så er jeg usikker på hva som skal gjøres

**Comment by thomiz** [comment]
@kennethmyhra 

Det må opprettes sider i IG verktøyet på SIMPLIFIER. Disse kan være en enkel rendring av en .md fil, eller det kan legges manuelt inn i verktøyet (Guides - edit):
![image](https://user-images.githubusercontent.com/6229665/129565590-cc70777f-dc6d-4b38-aa98-70849a8392e3.png)

Det må uansett legges til en side for at en opplastet .md fil skal rendres som en del av IG'en, men den siden kan bare inneholde en kodelinje hvis selve teksten lastes opp som .md:
`{{render:[sidenavn]}}`

**Comment by kennethmyhra** [comment]
Har oppdatert IG på Simplifier samt oppdatert dokumentasjonen in-line i profilene DocumentReference og Composition, se #81
