### ISSUE TITLE
NoBasisDocumentReferenceType er fremdeles Draft?

### ISSUE THREAD

**Issue by thomiz** [HL7Norway/basisprofiler-r4#65]
Skal den også være active, altså endel av no-basis pakken?
Den må også nevnes i Implementasjonsguiden.

**Comment by kennethmyhra** [comment]
Ble satt til active her: #59

**Comment by thomiz** [comment]
Ligger som ikke aktive SIMPLIFIER...

**Comment by thomiz** [comment]
DocumentReferenceType altså

**Comment by kennethmyhra** [comment]
Ah.. jeg som misforstår
