### ISSUE TITLE
Legge inn nye kodeverk i no-basis-Organization

### ISSUE THREAD

**Issue by oaassv** [HL7Norway/basisprofiler-r4#69]
På TSK-møte 12.desember ble det besluttet at Volven-kodeverk 8624 og 8628 begge tas inn med slice på Organization.type. Endring kom med bakgrunn i at informasjonen inngår i nasjonal RESH-tjeneste for organisasjon.

**Comment by thomiz** [comment]
Det å legge til slices er vel å anse som non-breaking change, så dette kan publiseres i pakke 2.0.15 altså neste versjon.
