### ISSUE TITLE
NoBasisPractitioner - Kodeverk - Qualification

### ISSUE THREAD

**Issue by rockphotog** [HL7Norway/basisprofiler-r4#7]
Følgene kodeverk vurderes i NoBasisPractitioner/Qualification:

- Helsepersonellregisterets (HPR) klassifikasjon av spesialiteter (OID=7426)
- Kategori helsepersonell (OID=9060)
- Godkjenningstype HPR (OID=7704) (behov? Kjør debatt!)

Erstatter https://github.com/HL7Norway/basisprofiler-r3/issues/28

**Comment by ellgre** [comment]
Vi har så langt sett for oss følgende:
- qualification.code = 9060
- qualification.approvalType = 7704 (extension)
- qualification.specialty.code = 7426 (extension)

**Comment by rockphotog** [comment]
Høyttenkning: Kan man tenke seg at 9060 og 7426 kan leve side om side, mens 7704 er "metadata" til 7426?

**Comment by ellgre** [comment]
De fleste practitioners vil kun ha 9060 og 7704. Det er kun leger og tannleger som eventuelt kan ha 7426 og denne er knyttet til 7704. Hvis man ikke har 7704 med verdi autorisasjon så vil man ikke kunne ha en 7426. Hvis man i 7704 for eksempel har en studentlisens, vil det aldri finnes noen 7426.

**Comment by thomiz** [comment]
Alle tre kodeverkene ligger inne som hver sin slice i qualification.code i siste forslag til no-basis-Practitioner. Er litt usikker på om det var slik @ellgre så det for seg. Slik det er utformet nå er slicen åpen men det er bare mulig å ha en kode per qualification (ligger som begrensning i basisressursen). Man kan imidlertid ha hvor mange qualification elementer som trengs for å beskrive de kvalifikasjoner helsepersonellet har godkjent (og eventuelt andre).

**Comment by ellgre** [comment]
Jeg har sett på no-basis-Practitioner og det er noe sånt vi ser for oss. Kommer rekvisisjonsrett, tilleggskompetanse og eventuelt også utdanning noe sted? Savner også informasjon om perioder, turnus gjennomført og end reason. Er det noe som kommer etter hvert? Vi har brukt gd-practitioner-v01 og synes at den er virker ganske grei å bruke, men er klart åpen for andre varianter.

Vi lurer litt på hvordan vi skal løse de yrkesgruppene som er helsepersonell uten å ha godkjenning i HPR. Så langt gjelder dette logopeder og audiopedagoger. Disse må legges inn i egne kodeverk som benyttes for behandlere som har disse yrkesgruppene. Kan man for samme felt i FHIR bruke ulike kodeverk?

På tilsvarende måte vil vi også hente ut spesialiseringer som ikke finnes i HPR. Tenker da for eksempel på spesialiseringer for psykologer og fysioterapeuter som vedlikeholdes av profesjonsforeningene. Her er det også en utfordring med at disse spesialitetene ikke ligger i 7426,

**Comment by thomiz** [comment]
Sjekket i kode, denne er i orden.
