### ISSUE TITLE
Publisere no-basis på HL7 registry

### ISSUE THREAD

**Issue by rockphotog** [HL7Norway/basisprofiler-r4#8]
Erstatter https://github.com/HL7Norway/basisprofiler-r3/issues/23

Legge ut vår IG her når den er klar: https://www.fhir.org/guides/registry

EDIT: Redigerte lenken fra http -> https, da virker den.

**Comment by thomiz** [comment]
Når R4 versjonen er vedtatt bør den legges ut i registry.
JEg finner ikke lenger IG-registry på den lenken du har over her @rockphotog

**Comment by rockphotog** [comment]
Denne lenken fungerer, ser jo helt lik ut, hmm... @thomiz 

http://www.fhir.org/guides/registry/

**Comment by rockphotog** [comment]
Note to self:
https://github.com/FHIR/ig-registry
https://github.com/FHIR/ig-registry/blob/master/fhir-ig-list.json

**Comment by rockphotog** [comment]
Har begynt her:

https://github.com/HL7Norway/basisprofiler-r4/blob/Implementation-Guide-Registry/no-basis-fhir-ig-list.json

**Comment by rockphotog** [comment]
Er nå i master:
https://github.com/HL7Norway/basisprofiler-r4/blob/master/no-basis-fhir-ig-list.json

**Comment by rockphotog** [comment]
Pull request: https://github.com/FHIR/ig-registry/pull/53 - venter på tommel opp eller ned.

**Comment by thomiz** [comment]
Funksjonaliteten må inn i publiserings-scriptet
