### ISSUE TITLE
no-basis-Encounter

### ISSUE THREAD

**Issue by thomiz** [HL7Norway/basisprofiler-r4#97]
* no-basis-Encounter

**Comment by oaassv** [comment]
Publisert

**Comment by thomiz** [comment]
Den er ikke publisert, bare lagt til Appointment branchen

**Comment by thomiz** [comment]
Feil i class, du kan ikke slice non-repeating element.

**Comment by thomiz** [comment]
Dette er en Feature issue, det vil si at den skal egentlig brukes til å samle all innsatsen vi gjøre på no-basis-Encounter. Issue kan først lukkes når no-basis-Encounter er ferdig utviklet, bugs er lukket, dokumentasjonen er ferdig og profilen er satt til Active og med i en ny release av no-basis.

**Comment by thomiz** [comment]
Foreslår å lukke denne og slette forslag til no-basis-Encounter fra repoet. @oaassv

**Comment by oaassv** [comment]
Ok

**Comment by thomiz** [comment]
> Ok

Vi kan ikke lukke før vi faktisk har tatt bort no-basis-Encounter fra kildekoden. Vi lager en egen 2.2.0-release branch for det.

**Comment by thomiz** [comment]
Denne skal kanskje også slettes @oaassv?  
[introWorkflow.md](https://github.com/HL7Norway/basisprofiler-r4/blob/Appointment-2023/input/introWorkflow.md)

**Comment by oaassv** [comment]
@thomiz - det er relevant tekst, så greit å ta vare på til når Encounter og EpisodeOfCare-profilene er på plass. Men i og for seg kanskje nyttig informasjon selv om vi foreløpig kun har Appointment-profil, da den er med å forklare scopingen av Appointment i forhold til Encounter og EoC?

**Comment by thomiz** [comment]
Enig tror vi beholder den og tar den inn i Implementasjonsguiden.

**Comment by thomiz** [comment]
Slettet no-basis-Encounter fra Appointment-2023 branch
